# Generated by Django 4.1.2 on 2023-02-18 16:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=48)),
                ("adress", models.CharField(max_length=48)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
