# Generated by Django 4.1.2 on 2023-02-18 22:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=48)),
                ("adress", models.CharField(max_length=48)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Roles",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=48, unique=True)),
                (
                    "permission",
                    models.IntegerField(
                        choices=[
                            ("0", "Default"),
                            ("1", "Studant"),
                            ("3", "Assistent"),
                            ("5", "Teacher"),
                            ("7", "Admin"),
                            ("9", "Owner"),
                        ],
                        default="0",
                    ),
                ),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="campus.campus"
                    ),
                ),
            ],
        ),
    ]
