# Generated by Django 4.1.2 on 2023-02-22 17:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subjects",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=48)),
            ],
        ),
        migrations.CreateModel(
            name="SubjectsStudants",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "test_1",
                    models.DecimalField(
                        decimal_places=1, default=None, max_digits=3, null=True
                    ),
                ),
                (
                    "test_2",
                    models.DecimalField(
                        decimal_places=1, default=None, max_digits=3, null=True
                    ),
                ),
                (
                    "test_3",
                    models.DecimalField(
                        decimal_places=1, default=None, max_digits=3, null=True
                    ),
                ),
                (
                    "test_4",
                    models.DecimalField(
                        decimal_places=1, default=None, max_digits=3, null=True
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subjects.subjects",
                    ),
                ),
            ],
        ),
    ]
